[package]
name = "util-error"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
rlp = { git = "https://github.com/paritytech/parity-common" }
ethereum-types = "0.3"
error-chain = { version = "0.12", default-features = false }
rustc-hex = "1.0"
