[package]
name = "stream-encoder"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "trait for encoded streams"
license = "GPL-3.0"

[dependencies]
elastic-array = "0.10"
